insert into public.ai_generation_jobs (
  id,
  user_id,
  subject_id,
  topic_id,
  kind,
  status,
  prompt_metadata,
  output_json,
  model_name,
  token_usage
)
values (
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
  null,
  null,
  null,
  'lesson',
  'published',
  '{"subject":"IGCSE Mathematics","topic":"Fractions","level":"Foundation","duration":"60 minutes"}'::jsonb,
  '{"lessonId":"LESSON-001","title":"Fractions Foundations"}'::jsonb,
  'mock-provider',
  128
)
on conflict (id) do nothing;

insert into public.ai_generated_lessons (
  id,
  job_id,
  title,
  lesson_id,
  subject,
  topic,
  qualification,
  level,
  duration,
  output_json,
  status
)
values (
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
  'Fractions Foundations',
  'LESSON-001',
  'IGCSE Mathematics',
  'Fractions',
  'Cambridge IGCSE',
  'Foundation',
  '60 minutes',
  '{"learningObjectives":["Simplify fractions"],"teacherExplanation":"Explain simplification and equivalence"}'::jsonb,
  'published'
)
on conflict (id) do nothing;

insert into public.ai_generated_questions (
  id,
  job_id,
  question_text,
  answer_options,
  correct_answer,
  explanation,
  mark_scheme,
  examiner_tip,
  common_mistake,
  topic,
  difficulty,
  marks,
  command_word,
  bloom_level,
  status,
  output_json
)
values (
  'cccccccc-cccc-cccc-cccc-cccccccccccc',
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
  'Simplify 12/18.',
  '["2/3","3/4","4/6","1/2"]'::jsonb,
  '2/3',
  'Divide the numerator and denominator by 6.',
  '["1 mark for correct simplification"]'::jsonb,
  'Show the common factor clearly.',
  'Forgetting to divide by the highest common factor.',
  'Fractions',
  'Foundation',
  2,
  'Simplify',
  'Apply',
  'published',
  '{"topic":"Fractions"}'::jsonb
),
(
  'dddddddd-dddd-dddd-dddd-dddddddddddd',
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
  'Convert 3/4 to a percentage.',
  '["25%","50%","75%","100%"]'::jsonb,
  '75%',
  'Multiply by 25 because 1/4 equals 25%.',
  '["1 mark for the correct percentage"]'::jsonb,
  'Use a known fraction-to-percentage conversion.',
  'Confusing 3/4 with 3/5.',
  'Fractions',
  'Foundation',
  2,
  'Convert',
  'Understand',
  'draft',
  '{"topic":"Fractions"}'::jsonb
),
(
  'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
  'What is 2/3 of 18?',
  '["6","9","12","15"]'::jsonb,
  '12',
  'Divide by 3 and multiply by 2.',
  '["1 mark for the correct answer"]'::jsonb,
  'Break the quantity into thirds first.',
  'Forgetting to multiply after dividing.',
  'Fractions',
  'Foundation',
  2,
  'Calculate',
  'Apply',
  'review',
  '{"topic":"Fractions"}'::jsonb
),
(
  'ffffffff-ffff-ffff-ffff-ffffffffffff',
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
  'Which fraction is equivalent to 0.5?',
  '["1/2","1/4","2/5","3/4"]'::jsonb,
  '1/2',
  '0.5 is equivalent to one half.',
  '["1 mark for the equivalent fraction"]'::jsonb,
  'Use the decimal place value.',
  'Thinking 0.5 is 1/4.',
  'Fractions',
  'Foundation',
  2,
  'Identify',
  'Understand',
  'approved',
  '{"topic":"Fractions"}'::jsonb
),
(
  '10101010-1010-1010-1010-101010101010',
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
  'Add 1/4 and 1/2.',
  '["3/4","2/4","1/4","1/2"]'::jsonb,
  '3/4',
  'Convert 1/2 to 2/4 before adding.',
  '["1 mark for the correct sum"]'::jsonb,
  'Use common denominators where needed.',
  'Adding numerators and denominators separately.',
  'Fractions',
  'Foundation',
  2,
  'Add',
  'Apply',
  'draft',
  '{"topic":"Fractions"}'::jsonb
);
