import Link from "next/link";
import { StatusBadge } from "@/components/teacher/StatusBadge";
import type { TeacherReviewItem } from "@/lib/teacher/types";

type ReviewCardProps = {
  item: TeacherReviewItem;
};

export function ReviewCard({ item }: ReviewCardProps) {
  return (
    <div className="rounded-3xl border border-slate-800 bg-slate-900/70 p-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-sm font-semibold uppercase tracking-[0.3em] text-amber-400">{item.contentType}</p>
          <h3 className="mt-2 text-lg font-semibold text-white">{item.title}</h3>
        </div>
        <StatusBadge status={item.status} />
      </div>

      <div className="mt-4 grid gap-3 text-sm text-slate-400 sm:grid-cols-2">
        <div><span className="text-slate-500">Subject:</span> {item.subject}</div>
        <div><span className="text-slate-500">Topic:</span> {item.topic}</div>
        <div><span className="text-slate-500">Created:</span> {new Date(item.createdAt).toLocaleDateString()}</div>
        <div><span className="text-slate-500">Generated by:</span> {item.generatedBy}</div>
      </div>

      <div className="mt-5 flex flex-wrap items-center justify-between gap-3">
        <p className="text-sm text-slate-400">Priority: <span className="font-semibold text-white">{item.priority}</span></p>
        <Link href={`/teacher/review/${item.id}`} className="rounded-full border border-amber-400/30 bg-amber-500/10 px-4 py-2 text-sm font-semibold text-amber-200 transition hover:bg-amber-500/20">View</Link>
      </div>
    </div>
  );
}
